### ISSUE TITLE
Could not pass event BlockBreakEvent to BentoBox v1.12.0

### ISSUE THREAD

**Issue by swerck** [BentoBoxWorld/AOneBlock#70]
#### Describe the bug

```
[20:52:45] [Server thread/ERROR]: Could not pass event BlockBreakEvent to BentoBox v1.12.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:295) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:254) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:151) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1185) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:887) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: org.bukkit.World.setBiome(IIILorg/bukkit/block/Biome;)V
        at world.bentobox.aoneblock.listeners.BlockListener.process(BlockListener.java:277) ~[?:?]
        at world.bentobox.aoneblock.listeners.BlockListener.lambda$onBlockBreak$1(BlockListener.java:189) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_211]
        at world.bentobox.aoneblock.listeners.BlockListener.onBlockBreak(BlockListener.java:189) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        ... 20 more
```

#### Steps to reproduce the behavior

I start the game with / oneblock then I am redirected to the OneBlock Map with a grass block. As soon as I break it down, I fall down and die. Then when I respawn and come back / oneblock I get the message in the chat "No safe place to teleport could be found." I already wanted to install Bbox version 1.13.1 but this only works with Spigot 1.15.2.

##### BentoBox Version (Mandatory)

```
[10:48:34] [Server thread/INFO]: Running SPIGOT 1.14.4.
[10:48:34] [Server thread/INFO]: BentoBox version: 1.12.0
[10:48:34] [Server thread/INFO]: Database: JSON
[10:48:34] [Server thread/INFO]: Loaded Game Worlds:
[10:48:34] [Server thread/INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[10:48:34] [Server thread/INFO]: caveblock-world (CaveBlock): Overworld, Nether, The End
[10:48:34] [Server thread/INFO]: oneblock_world (OneBlock): Overworld, Nether*
[10:48:34] [Server thread/INFO]: Loaded Addons:
[10:48:34] [Server thread/INFO]: AOneBlock 1.1.7 (ENABLED)
[10:48:34] [Server thread/INFO]: Border 1.0.7 (ENABLED)
[10:48:34] [Server thread/INFO]: BSkyBlock 1.12.0 (ENABLED)
[10:48:34] [Server thread/INFO]: CaveBlock 1.11.0 (ENABLED)
```

#### Plugins (Optional)

```
[10:57:50] [Server thread/INFO]: Plugins (52): PlaceholderAPI, ArmorStandCrashFix, SkinsRestorer, CreativeLore, Blocker, PlayerReport, HackerCage, InfiniteScoreboard, JoinMessage, CraftingStore, LuckPerms, WorldEdit, FastChunkPregenerator, AutoSmelt, WorldBorderAPI, AdvancedOreGenerator, IllegalStack, Votifier, ItemEdit, HidePlugins2, AutoPluginLoader, OpGuard, Vault, CreativeItemControl, BottledExp, ChatColor2, LuckPermsGUI, WorldGuard, EditableSign, Essentials, Jobs, BentoBox, FogusCore, WG-GUI, EssentialsChat, TimeIsMoney, SuperbVote, AdvancedClans, JetsMinions, SetTheSpawn, Multiverse-Core, GoldenCrates, QuickShop, ViaVersion, ViaBackwards, Plan, ViaRewind, ProtocolLib, Matrix, PluginHiderPlus, ExploitFixer, SuperVanish

```

**Comment by tastybento** [comment]
This error `Caused by: java.lang.NoSuchMethodError: org.bukkit.World.setBiome(IIILorg/bukkit/block/Biome;)V
` doesn't make sense and it seems like your server software is wrong somehow. Why don't you update to the latest version? You can download version from Paper https://papermc.io/downloads really easily.
